src/reports/urls.py
from django.shortcuts import render
from django.urls import path
from .views import (
    create_report_view,
    ReportListView,
    ReportDetailView,
    render_pdf_view,
    UploadTemplateView,
    csv_upload_view
    )

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('from_file/', UploadTemplateView.as_view(), name='from_file'),
    path('<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf/', render_pdf_view, name='pdf'),
]

src/reports_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sales/urls.py
from django.urls import path
from django.urls import path
from .views import (
    home_view,
    SaleListView,
    SaleDetailView,
)

app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SaleListView.as_view(), name='list'),
    path('sales/<pk>/', SaleDetailView.as_view(), name='detail'),
]

src/reports/models.py
from django.db import models
from django.db.models.fields import BLANK_CHOICE_DASH
from django.db.models.fields.files import ImageField
from profiles.models import Profile
from django.urls import reverse

# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ('created',)

src/reports/forms.py
from django import forms
from django.forms import fields
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

src/reports/views.py
from products.models import Product
from typing import List
from django.contrib import auth
from django.core.checks import messages
from django.forms.fields import JSONField
from django.http.request import HttpRequest
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from matplotlib.pyplot import autoscale
from profiles.models import Profile
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .utils import get_report_image
from .models import Report
from .forms import ReportForm
from django.views.generic import ListView, DetailView

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

from sales.models import Sale, Position, CSV
from products.models import Product
import csv
from django.utils.dateparse import parse_date
# Create your views here.

class ReportListView(ListView):
    model = Report
    template_name = 'reports/main.html'

class ReportDetailView(DetailView):
    model = Report
    template_name = 'reports/detail.html'

class UploadTemplateView(TemplateView):
    template_name = 'reports/from_file.html'

def csv_upload_view(request):
    print('file is being send')

    if request.method == 'POST':
        csv_file = request.FILES.get('file')
        obj = CSV.objects.create(file_name=csv_file)

        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)
            reader.__next__()
            for row in reader:
                data = "".join(row)
                data = data.split(',')
                data.pop()

                transaction_id = data[1]
                product = data[2]
                quantity = int(data[3])
                customer = data[4]
                date = parse_date(data[5])

                try:
                    product_obj = Product.objects.get(name=product)
                except Product.DoesNotExist:
                    product_obj = None

                print(product_obj)


    return HttpResponse()

@login_required
def create_report_view(request):
    form = ReportForm(request.POST or None)
    if request.is_ajax():
        #name = request.POST.get('name')
        #remarks = request.POST.get('remarks')

        image = request.POST.get('image')
        img = get_report_image(image)
        author = Profile.objects.get(user=request.user)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.image = img
            instance.author = author
            instance.save()

        #Report.objects.create(name=name, remarks=remarks, image=img, author=author)
        return JsonResponse({'msg':'send'})
    return JsonResponse({})

@login_required
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    obj = get_object_or_404(Report, pk=pk)
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # If download 
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # If display
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

src/reports/templates/reports/detail.html
{% extends "base.html" %}

{% block title %}
    {{object.name}}
{% endblock title %}

{% block content %}
    {% if object.image %}
        <img src="{{object.image.url}}" class="img-fluid" alt="{{object.name}}">
    {% endif %}
    <br>
    <h3>Remarks</h3>
    <p>{{obj.remarks}}</p>
    <hr>
    <p>author : <b>{{object.author.user.username}}</b></p>
    <p>created : <b>{{object.created}}</b></p>
{% endblock content %}

src/reports/templates/reports/from_file.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
upload sales files
{% endblock title %}

{% block content %}
    <h5>Upload your sales documentation</h5>
    <br>
    <form id="my-dropzone" class="dropzone dz">
        {% csrf_token %}
        <div class="fallback">
            <input name="file" type="file" multiple />
        </div>
    </form>
{% endblock content %} 

src/reports/templates/reports/main.html
{% extends "base.html" %}

{% block title %}
    reports
{% endblock title %}

{% block content %}
    reports
    <hr>
    {% for obj in object_list %}
        <div class="card mb-3">
        {% if obj.image %}        
            <img src="{{obj.image.url}}" class="card-img-top" alt="{{obj.name}}">
        {% endif %}
        <div class="card-body">
                <h5 class="card-title">{{obj.name}}</h5>
                <p class="card-text">{{obj.remarks|truncatewords:2}}</p>
                <a href={{obj.get_absolute_url}} class="btn btn-primary">details</a>
                <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-primary">pdf</a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

src/reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>PDF {{obj.name}}</title>
  <style>
    .image {
        width: 100%;
        height: auto;
    }
  </style>
</head>
<body>
    <h1>{{obj.name}}</h1>
    <hr>
    <img src={{obj.image.path}} class="image">
    <br>
    <h3>Remarks</h3>
    <p>{{obj.remarks}}</p>
    <hr>
    <p>author : <b>{{obj.author.user.username}}</b></p>
    <p>created : <b>{{obj.created}}</b></p>
</body>
</html>